<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Edit</name>
   <tag></tag>
   <elementGuidId>e6b1b97c-0f25-40e7-8972-24ac60db0d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.list-group-item.list-group-item-info.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/section/table/tbody/tr/td[9]/div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ae6e71d0-306c-4538-9473-c3c6dd5df48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item list-group-item-info ng-binding</value>
      <webElementGuid>0ab9f13f-64ae-462e-9434-27fed5efcf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>edit(user)</value>
      <webElementGuid>f3dabb1a-6e43-4fa5-a05a-79e7caf7a798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>can('update_user') || hasRole('ekare_admin')</value>
      <webElementGuid>b462d2ac-d132-4728-8338-07a0164bf4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     Edit
                  </value>
      <webElementGuid>9b8df613-e90d-4370-b8a2-74e3c728b5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;page-content-wrapper&quot;]/section[@class=&quot;users table-responsive&quot;]/table[@class=&quot;table-header table table-striped table-hover&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[9]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;list-group-item list-group-item-info ng-binding&quot;]</value>
      <webElementGuid>0b22edcb-4adb-47d9-92a7-66a3f334be27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/section/table/tbody/tr/td[9]/div/ul/li[2]</value>
      <webElementGuid>ea8181e2-f06d-4e04-ba71-de4ff54b9738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>cbed20c4-387b-4ac6-b65a-fa307c3601fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/ul/li[2]</value>
      <webElementGuid>3c67e8c5-6e12-4540-aad5-1b1061526654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                     Edit
                  ' or . = '
                     Edit
                  ')]</value>
      <webElementGuid>51bb424e-06cd-4bff-aece-1993497ba00b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
