<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeOther - Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeOther</value>
      <webElementGuid>efbbe989-d5c3-4f82-ad43-330e0cbd422d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f4b4f4c-b048-4284-a9d9-a15e953b88a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6442d58e-ffeb-46d8-8cd1-7d8570e27fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>836.0</value>
      <webElementGuid>06645660-860f-4247-b20b-10f2ba2a5d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>96738868-bc4e-47a4-ace4-892baf7dc818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap</value>
      <webElementGuid>6697cf1d-4265-4dc9-8825-6d00a3b99ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap</value>
      <webElementGuid>a210824a-0ebc-4844-bb53-9d1e168b17e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>780.0</value>
      <webElementGuid>1bc8a49c-e119-4569-a4a2-a11093787b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>e5046041-61ba-4805-b3a7-6b6fb367e0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>366.0</value>
      <webElementGuid>2e44b4bf-57ac-4a1a-b06e-5fa5f4d63e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[4]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]</value>
      <webElementGuid>1dfcafb9-9c81-4c2f-820d-000b89b4532e</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeOther' and @label = 'Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap' and @name = 'Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap']</locator>
   <locatorCollection>
      <entry>
         <key>NAME</key>
         <value>Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[4]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeOther</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeOther[`enabled == 1 AND label == 'Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap' AND name == 'Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap'`]</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeOther' AND enabled == 1 AND label == 'Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap' AND name == 'Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap'</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeOther' and @label = 'Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap' and @name = 'Treatment record Dressing Yes (per protocol) Debridement None Pressure redistribution Yes Comments Wound care protocol CLEANSING Anti-Bacterial Soap']</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
